### ISSUE TITLE
getting repeated tokens within topics

### ISSUE THREAD

**Issue by sambfloyd** [jhlau/hdp-wsi#1]
I'm trying this on some new input and I'm getting output with repeated tokens (such as _give_ and _baby_):

baby.n: baby n't look xxx want bear give look_#-1 yeah give_#-1
baby.n: baby mommy put put_#-1 horse hold daddy hold_#-1 pig mommy_#-2
baby.n: baby baby_#2 baby_#-2 baby_#-1 baby_#1 rock baby_#-3 baby_#3 bye rock_#-1

I thought this was not supposed to happen because the topics should just be a list of the high probability words so it wouldn't separate the tokens? 
[baby.txt](https://github.com/jhlau/hdp-wsi/files/2936879/baby.txt)

I've attached the input for this word. Any tips would be appreciated!!!!

**Comment by jhlau** [comment]
In the original paper (http://www.aclweb.org/anthology/E12-1060), we mentioned that we also introduce positional word features into the model:

> These senses are learnt using HDP with both positional word features (e.g. husband #-1, indicating the lemma husband to the immediate left of the target word) ...

When we're seeing baby_#2 in the topic words, that means the word _baby_ tends to occur 2 positions after the original target word _baby_. And that seems plausible looking at your data, e.g.:

> right i take care of the _baby_ the _baby_ 's fine she 's sleeping .
> he be hold a little _baby_ a little _baby_ dog just like you hold ana .

For words like _give_ and _n't_, you probably want to filter these function words as they are going to occur very frequently.

**Comment by sambfloyd** [comment]
Thank you for the function word advice and for clarifying this!

In case anyone wants to remove positional information, I just commented this out in the AddContextWord.py script, this is starting line 32:

    if word == pageboundary:
        #print context word
        for pos in target_word_pos:
            for i in range(1, 4):
                #left i'th neighbour
                if (pos-i) >= 0:
                    if words_in_doc[pos-i].count("#") != 2:
                        print words_in_doc[pos-i] #+ "_#" + str(-1*i) #SF TOOK OUT POSITION FEATURE

                #right i'th neghbour
                if (pos+i) < word_pos:
                    if words_in_doc[pos+i].count("#") != 2:
                        print words_in_doc[pos+i] #+ "_#" + str(i) #SF TOOK OUT POSITION FEATURE
